# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
export JAVA_HOME="/usr/lib/jvm/$(archlinux-java get)"
PATH="$PATH:/opt/bin:$JAVA_HOME/bin"
PATH="$PATH:$HOME/.cabal/bin"
export VISUAL="/usr/bin/nvim"
export EDITOR="/usr/bin/nvim"

if [[ -n $SSH_CONNECTION ]] && [[ -z $TMUX ]]; then
  tmux -u attach -t ssh || tmux -u new -s ssh
fi

# Increase memory of sbt
export SBT_OPTS="-Xmx4G"

# Set locale
export LANG=en_GB.UTF-8
export LANGUAGE=en_GB
export LC_CTYPE="en_GB.UTF-8"
export LC_NUMERIC="en_GB.UTF-8"
export LC_TIME="en_GB.UTF-8"
export LC_COLLATE="en_GB.UTF-8"
export LC_MONETARY=sv_SE.UTF-8
export LC_MESSAGES="en_GB.UTF-8"
export LC_PAPER=sv_SE.UTF-8
export LC_NAME=sv_SE.UTF-8
export LC_ADDRESS=sv_SE.UTF-8
export LC_TELEPHONE=sv_SE.UTF-8
export LC_MEASUREMENT=sv_SE.UTF-8
export LC_IDENTIFICATION=sv_SE.UTF-8
export LC_ALL=

# Enable beets completion if beets is installed
type &>/dev/null && eval "$(beet completion)"

# Set colours for TTY
if [ "$TERM" = "linux" ]; then
  /bin/echo -e "
  \e]P0000000
  \e]P1d53100
  \e]P22fd400
  \e]P3ffc000
  \e]P40042b6
  \e]P5df005b
  \e]P600a4f0
  \e]P7c0c0c0
  \e]P83b3b3b
  \e]P9ff331c
  \e]PA3cff00
  \e]PBfff00a
  \e]PC0071ff
  \e]PDff0098
  \e]PE00d3ff
  \e]PFffffff
  "
  # get rid of artifacts
  #clear
fi

# If running from tty1 start sway
if [ "$(tty)" = "/dev/tty1" ]; then
    # Set QT platform for Wayland to fix slowdown issue
    # github.com/qutebrowser/qutebrowser/issues/4857
    export QT_QPA_PLATFORM=wayland

    export XDG_CURRENT_DESKTOP=sway
    export XDG_SESSION_TYPE=wayland

    #export MOZ_ENABLE_WAYLAND=1
    #export QT_QPA_PLATFORM=wayland-egl
    #export CLUTTER_BACKEND=wayland
    #export ECORE_EVAS_ENGINE=wayland-egl
    #export ELM_ENGINE=wayland_egl
    #export SDL_VIDEODRIVER=wayland
    #export _JAVA_AWT_WM_NONREPARENTING=1
    #export NO_AT_BRIDGE=1

    exec systemd-cat --identifier=sway sway
fi

