## Beets settings ##
directory: ~/Music
library: ~/.config/beets/musiclibrary.db

import:
  move: yes
  log: ~/.config/beets/imports.log
  languages: en

per_disc_numbering: yes
original_date: yes
languages: en

match:
  preferred:
    media: ['CD', 'Digital Media|File']
    original_year: yes

paths:
  default: %the{$albumartist}/%if{$original_year,$original_year,$year} - $album%aunique{}/%if{$multidisc,Disc $disc/}$track $title
  singleton: %the{$artist}/Non-Album/$title

## Plugin configuration ##
plugins:
  #- alternatives
  #- bandcamp
  - bandcamp
  #- chroma
  - convert
  #- discogs
  - duplicates
  - edit
  - embedart
  - extrafiles
  - fetchart
  - fromfilename
  - inline
  #- lastimport
  - lyrics
  - mbsubmit
  - mbsync
  - missing
  - permissions
  - random
  - replaygain
  - substitute
  - the
  - unimported
  - yapl

acoustid:
  apikey: 77UD6iWvfo

alternatives:
  lossy:
    directory: /mnt/data/MusicLossy
    formats: aac mp3
    query: "path+"
    removable: true

convert:
  dest: /mnt/data/MusicLossy
  never_convert_lossy_files: yes
  format: aac

edit:
  itemsfields: track title artist album path

embedart:
  maxwidth: 600

extrafiles:
  patterns:
    artworkdir:
      - '[sS]cans/'
      - '[sS]can/'
      - '[aA]rtwork/'
      - '[cC]over/'
      - '[cC]overs/'
      - '[pP]icutres/'
    artworkfiles:
      - '*.png'
      - '*.jpg'
      - '*.jpeg'
      - '*.gif'
      - '*.pdf'
    datafiles:
      - '*.log'
      - '*.txt'
      - '*.md5'
      - '*.ffp'
      - '*.cue'
      - '*.CUE'
      - '*.nfo'
      - '*.st5'
      - '*.auCDtect'
      - '*.accurip'
      - '*.sfv'
      - '*.xml'
    extradir:
      - '[eE]xtras/'
  paths:
    artworkdir: $albumpath/artwork
    extradir: $albumpath/data
    artworkfiles: $albumpath/artwork/$filename
    datafiles: $albumpath/data/$filename

fetchart:
  sources:
    - filesystem
    - coverart
    - itunes
    - amazon
    - albumart
    - wikipedia

# Inline Plugin
item_fields:
  multidisc: 1 if disctotal > 1 else 0

album_fields:
  length: |
    sum(map(lambda i: i.length, items))

  formats: |
    ', '.join(sorted(set(map(lambda i: i.format, items))))
  formatn: |
    len(set(map(lambda i: i.format, items)))

lastfm:
  user: nichobi

replaygain:
  auto: yes
  backend: ffmpeg
  overwrite: yes

yapl:
  input_path: /home/nichobi/Music/playlists/
  output_path: /home/nichobi/Music/playlists/
  relative: true

