ZCACHEDIR=${XDG_CACHE_HOME:-~/.cache}/zsh
ADOTDIR=$ZCACHEDIR/antigen
fpath=($ZDOTDIR/completion $fpath)
#ANTIGEN_LOG=$ADOTDIR/log
source /usr/share/zsh/share/antigen.zsh

antigen bundles <<EOBUNDLES
  shrink-path
  jeffreytse/zsh-vi-mode
  fzf
  Aloxaf/fzf-tab
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting # Must be last!
EOBUNDLES
antigen apply

# Rebind history search, fix for:
# https://github.com/jeffreytse/zsh-vi-mode/issues/127
function zvm_after_init() {
  zvm_bindkey viins '^R' fzf-history-widget
}

setopt interactive_comments # Comments in interactive shell
setopt auto_cd              # cd by typing directory name if it's not a command
setopt auto_pushd           # Automatically pushd when changing directory
setopt pushd_ignore_dups    # Ignore duplicate directories in pushd
#setopt pushdminus           # 

for f in $ZDOTDIR/zshrc.d/*.zsh; do
  source $f
done
